const extraPosts = [{
  _id: '1',
  title: 'asd',
  author: 'bwqvq',
  description: 'asd',
  type: 'standard',
  createdAt: 'asdasd',
  slug: 'asd',
  postType: 'standard',
  meta: {
    haha: '',
  },
  time: 'asd',
  public: '',
  image: '/images/thumbs/masonry/lamp-400.jpg',
  tags: [{
    _id: '64',
    name: 'asd',
    slug: 'asdasd',
  },
  {
    _id: '661243',
    name: 'asd',
    slug: 'asdasd',
  },
  ],
},
{
  _id: '3',
  author: 'bwqvq',
  image: '/images/thumbs/masonry/lamp-400.jpg',
  title: 'asd',
  description: 'asd',
  time: 'fav',
  type: 'standard',
  slug: 'asd',
  postType: 'standard',
  createdAt: 'asdasd',
  tags: [{
    _id: '624',
    name: 'asd',
    slug: 'asdasd',
  },
  {
    _id: '676dg',
    name: 'asd',
    slug: 'asdasd',
  },
  ],
},
{
  _id: '4',
  slug: 'asd',
  time: 'asfnb',
  author: 'bwqvq',
  title: 'asd',
  description: 'asd',
  postType: 'standard',
  image: '/images/thumbs/masonry/lamp-400.jpg',
  type: 'standard',
  createdAt: 'asdasd',
  tags: [{
    _id: '14',
    name: 'asd',
    slug: 'asdasd',
  },
  {
    _id: '26',
    name: 'asd',
    slug: 'asdasd',
  },
  ],
},
];

export default extraPosts;
